/**
 * Standard Sports & Recreational Activities Configuration
 * Extensible design for adding new sports and activities
 */

export const ACTIVITIES = [
  {
    id: 'padel',
    name: 'بادل',
    nameEn: 'Padel',
    icon: '🎾',
    badgeColor: '#0D6B4F',
    defaultBookingType: 'time_slot',
    defaultDuration: 90,
    subTypes: [
      { id: 'panoramic', name: 'ملعب بانورامي' },
      { id: 'indoor', name: 'مغلق (Indoor)' },
      { id: 'outdoor', name: 'مفتوح (Outdoor)' },
    ],
    popular: true,
  },
  {
    id: 'football',
    name: 'كرة القدم',
    nameEn: 'Football',
    icon: '⚽',
    badgeColor: '#1B8055',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: '5v5', name: 'خماسي (5v5)' },
      { id: '7v7', name: 'سباعي (7v7)' },
      { id: '11v11', name: 'قانوني (11v11)' },
    ],
    popular: true,
  },
  {
    id: 'tennis',
    name: 'تنس أرضي',
    nameEn: 'Tennis',
    icon: '🎾',
    badgeColor: '#B8860B',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: 'hard', name: 'أرضية صلبة' },
      { id: 'clay', name: 'ترابية (Clay)' },
      { id: 'grass', name: 'عشبية' },
    ],
    popular: true,
  },
  {
    id: 'swimming',
    name: 'سباحة وحصص مائية',
    nameEn: 'Swimming',
    icon: '🏊',
    badgeColor: '#0284C7',
    defaultBookingType: 'session',
    defaultDuration: 60,
    defaultCapacity: 20,
    subTypes: [
      { id: 'olympic', name: 'مسبح أولمبي' },
      { id: 'lanes', name: 'حارات سباحة حرة' },
      { id: 'session', name: 'جلسات تدريب وتأهيل' },
      { id: 'kids', name: 'مسبح أطفال' },
    ],
    popular: true,
  },
  {
    id: 'basketball',
    name: 'كرة السلة',
    nameEn: 'Basketball',
    icon: '🏀',
    badgeColor: '#EA580C',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: 'indoor', name: 'صالة مغطاة' },
      { id: 'outdoor', name: 'ملعب خارجي' },
    ],
    popular: true,
  },
  {
    id: 'volleyball',
    name: 'كرة الطائرة',
    nameEn: 'Volleyball',
    icon: '🏐',
    badgeColor: '#9333EA',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: 'indoor', name: 'صالة مغطاة' },
      { id: 'beach', name: 'طائرة شاطئية' },
    ],
    popular: false,
  },
  {
    id: 'badminton',
    name: 'ريشة طائرة',
    nameEn: 'Badminton',
    icon: '🏸',
    badgeColor: '#16A34A',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: 'court', name: 'ملعب ريشة مغلق' },
    ],
    popular: false,
  },
  {
    id: 'table_tennis',
    name: 'تنس طاولة',
    nameEn: 'Table Tennis',
    icon: '🏓',
    badgeColor: '#DC2626',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: 'table', name: 'طاولة احترافية' },
    ],
    popular: false,
  },
  {
    id: 'fitness',
    name: 'لياقة وبيلاتس وجيم',
    nameEn: 'Fitness & Gym',
    icon: '🏋️',
    badgeColor: '#4F46E5',
    defaultBookingType: 'session',
    defaultDuration: 60,
    defaultCapacity: 15,
    subTypes: [
      { id: 'crossfit', name: 'كروس فيت (Crossfit)' },
      { id: 'gym_day', name: 'تذكرة يومية للجيم' },
      { id: 'aerobics', name: 'أيروبكس ولياقة' },
    ],
    popular: true,
  },
  {
    id: 'yoga',
    name: 'يوغا وبيلاتس',
    nameEn: 'Yoga & Pilates',
    icon: '🧘',
    badgeColor: '#059669',
    defaultBookingType: 'session',
    defaultDuration: 60,
    defaultCapacity: 12,
    subTypes: [
      { id: 'yoga_session', name: 'جلسة يوغا وتأمل' },
      { id: 'pilates', name: 'بيلاتس ريفورمر' },
    ],
    popular: false,
  },
  {
    id: 'martial_arts',
    name: 'فنون قتالية',
    nameEn: 'Martial Arts',
    icon: '🥋',
    badgeColor: '#B91C1C',
    defaultBookingType: 'session',
    defaultDuration: 60,
    defaultCapacity: 15,
    subTypes: [
      { id: 'kickboxing', name: 'كيك بوكسينغ' },
      { id: 'karate', name: 'كاراتيه ودفاع عن النفس' },
    ],
    popular: false,
  },
  {
    id: 'other',
    name: 'أنشطة أخرى',
    nameEn: 'Other Activities',
    icon: '🎯',
    badgeColor: '#6B7280',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
    subTypes: [
      { id: 'general', name: 'نشاط ترفيهي عام' },
    ],
    popular: false,
  },
];

export const getActivityById = (id) => {
  return ACTIVITIES.find((a) => a.id === id) || {
    id,
    name: id || 'نشاط رياضي',
    nameEn: id,
    icon: '🏆',
    badgeColor: '#0D6B4F',
    defaultBookingType: 'time_slot',
    defaultDuration: 60,
  };
};
